name: Push container

on:
    workflow_call:
        inputs:
            package:
                required: true
                type: string
            run-cmd:
                required: true
                type: string
            tags:
                required: true
                type: string

jobs:
    push-container:
        runs-on: ubuntu-latest
        env:
            CAN_PUSH: ${{ secrets.DOCKER_PASSWORD != '' && secrets.DOCKER_USERNAME != '' }}
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            - uses: docker/login-action@v3
              if: env.CAN_PUSH == 'true'
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push container
              env:
                PUSH: ${{ (env.CAN_PUSH == 'true') && '--push' || '' }}
              run: |
                echo "Building: '${{ inputs.package }}'"
                echo "Tags: ${{ inputs.tags }}"

                npm run i
                npm run ${{ inputs.run-cmd }}
                node scripts/flows.js
                docker buildx build -f packages/${{ inputs.package }}/Dockerfile --platform linux/amd64 ${{ inputs.tags }} . --no-cache ${{ env.PUSH }}

