name: Yaml Validation

on: [push, pull_request]

concurrency:
    group: validation-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    yaml_validation_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Lint yaml files
              uses: ibiqlik/action-yamllint@v3
